---
title: Server and Client Sequence
---
sequenceDiagram
    actor user as Web Browser
    participant svelte as Front End
    participant flask as Back End
    participant db@{ "type" : "database" } as Storage
    participant other@{ "type" : "boundary" } as Other ActivityPub Server

    Note over user,db: ユーザーが投稿するにはログインを必須とする
    user->>+flask: ログインリクエスト
    flask->>db: アカウントの存在の問い合わせ
    db->>flask: アカウントの存在の返答

    alt アカウント存在無し。またはアカウント認証通らず
        flask->>svelte: HTTPSステータス 401
        svelte->>svelte: 401ページへ遷移
        svelte-->>user: 認証試行失敗
    else 認証試行成功
        flask->>svelte: HTTPSステータス 200
        svelte->>flask: ユーザーのタイムラインを要求
        flask->>db: ユーザーのフォロー投稿を要求
        flask-->>other: ユーザーのフォロー投稿を要求
        db->>flask: フォロー投稿情報
        other-->>flask: フォロー投稿情報
        flask->>flask: 投稿を時系列順に生成
        flask->>-svelte: 投稿一覧
        svelte->>svelte: 投稿フォーム, 投稿一覧を生成
        svelte-->>user: 投稿フォーム, 投稿一覧表示
        par 投稿更新通知
            svelte->>flask: 追加投稿確認要求
            flask-->>db: 追加分の要求
            flask-->>other: 追加分の要求
            db-->>flask: 追加分の返答
            other-->>flask: 追加分の返答
            flask-->>flask: 追加分の生成
            flask->>svelte: 追加分の投稿
            svelte->>user: 追加分の投稿表示リンク作成
            user->>svelte: 追加分の投稿表示を要求
            svelte->>svelte: 追加分の投稿を投稿一覧に追記
            svelte->>user: 投稿一覧の更新表示
        and リプライ（投稿への返信通知）
            svelte->>flask: リプライ確認要求
            flask->>db: ユーザーの投稿に対する返信投稿の確認またはユーザーを指名した投稿確認
            flask-->>other: ユーザーを指名した投稿の確認
            db->>flask: ユーザーの投稿に対する返信の個数
            other-->>flask: ユーザーを指名した投稿
            flask->>flask: 返信や指名の数え上げ
            flask->>svelte: 返信や指名の個数
            svelte->>svelte: 返信や指名の通知の生成
            svelte-->>user: 返信や指名の通知
        end
    end
